const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.resolve(__dirname,'../Code.gs'),'utf8');
function fixture(){
 const props={},sheets=new Map(),triggers=[];let created=0,books=0,publicMime=null;
 function makeSheet(name){const rows=[];const sheet={rows,getLastRow:()=>rows.length,getLastColumn:()=>Math.max(0,...rows.map(r=>r.length)),setFrozenRows(){},setName(n){sheets.delete(name);name=n;sheets.set(name,sheet);return sheet;},getRange(r,c,n,m){return {setValues(values){assert.equal(values.length,n);for(let i=0;i<n;i++){rows[r-1+i]??=[];for(let j=0;j<m;j++)rows[r-1+i][c-1+j]=values[i][j];}return this;},getDisplayValues(){return Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>String(rows[r-1+i]?.[c-1+j]??'')));},setFontWeight(){}};},getDataRange(){return sheet.getRange(1,1,rows.length,sheet.getLastColumn());}};sheets.set(name,sheet);return sheet;}
 const book={getId:()=> 'test-sheet',getUrl:()=> 'https://docs.google.com/spreadsheets/d/test-sheet/edit',getSheets:()=> [...sheets.values()],getSheetByName:n=>sheets.get(n),insertSheet:makeSheet};
 const directory='學年度,代碼,學校名稱,公/私立,縣市名稱,地址,電話,網址\n114,1,市立鳳新高中,公立,[12]高雄市,高雄市鳳山區,123,https://example.test/fhsh\n114,2,市立高雄高中,公立,[12]高雄市,高雄市三民區,123,https://example.test/kshs\n114,3,市立台南高中,公立,[11]臺南市,臺南市,123,https://example.test/other';
 const ctx={console:{log(){}},Set,Map,Math,Date,JSON,Error,Object,Array,PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k],setProperty:(k,v)=>props[k]=v})},SpreadsheetApp:{getActiveSpreadsheet:()=>null,create(title){assert.equal(title,'鳳新高中各科題庫');books++;makeSheet('Sheet1');return book;},openById(id){assert.equal(id,'test-sheet');return book;},flush(){}},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},Utilities:{parseCsv:s=>s.trim().split(/\r?\n/).map(r=>r.split(',')),formatDate:()=> '2026-10-08 06:00:00'},UrlFetchApp:{fetch(url){assert.match(url,/stats.moe.gov.tw\/files\/school\/114\/high.csv/);return{getResponseCode:()=>200,getContentText:()=>directory};}},ScriptApp:{getProjectTriggers:()=>[...triggers],deleteTrigger(t){triggers.splice(triggers.indexOf(t),1);},newTrigger(handler){const t={handler,getHandlerFunction:()=>handler};const chain={};for(const key of ['timeBased','atHour','nearMinute','everyDays','inTimezone'])chain[key]=v=>{t[key]=v??true;return chain;};chain.create=()=>{triggers.push(t);created++;return t;};return chain;},getService:()=>({getUrl:()=>null})},ContentService:{MimeType:{CSV:'csv'},createTextOutput:text=>({text,setMimeType(m){publicMime=m;return this;}})}};
 vm.createContext(ctx);vm.runInContext(source,ctx);return{ctx,props,sheets,triggers,getBooks:()=>books,getCreated:()=>created,getMime:()=>publicMime};
}
const f=fixture();const result=f.ctx.initializeStudyWorkspace();assert.equal(f.getBooks(),1);assert.equal(f.sheets.get('題庫').getLastRow(),31);assert.equal(f.sheets.get('歷屆考題').getLastRow(),1);assert.equal(f.sheets.get('歷屆考題').getLastColumn(),17);assert.equal(f.triggers.length,0);assert.match(result.triggerStatus,/尚未安裝/);assert.match(result.directoryStatus,/2 校/);assert.ok(!f.sheets.get('學校名錄').rows.some(r=>r[0]==='台南高中'));assert.ok(f.sheets.get('學校名錄').rows.some(r=>r[0]==='鳳新高中'&&r[1]==='https://example.test/fhsh'));
f.props.AI_API_KEY='fake-key-test-only';f.props.EXAM_SCOPES_JSON='{"英文":"文法"}';f.ctx.initializeStudyWorkspace();assert.equal(f.getBooks(),1);assert.equal(f.sheets.get('題庫').getLastRow(),31);assert.equal(f.triggers.length,1);assert.equal(f.triggers[0].atHour,6);
f.ctx.initializeStudyWorkspace();assert.equal(f.getBooks(),1);assert.equal(f.triggers.length,1);assert.equal(f.sheets.get('題庫').getLastRow(),31);
const output=f.ctx.doGet({parameter:{type:'questions'}});assert.equal(f.getMime(),'csv');assert.ok(output.text.startsWith('\uFEFF'));assert.match(output.text,/FX-030/);assert.ok(!output.text.includes('fake-key-test-only'));
const past=f.ctx.doGet({parameter:{type:'past'}});assert.equal(past.text.split('\r\n').length,1);assert.match(past.text,/來源網址/);
assert.throws(()=>f.ctx.doGet({parameter:{type:'使用說明'}}),/不支援/);assert.throws(()=>f.ctx.doGet({parameter:{type:'__proto__'}}),/不支援/);
console.log('PASS: standalone Sheet bootstrap, 30 seeds, empty past sheet, official-directory mapping, idempotent setup, credential-gated triggers, allowlisted read-only CSV.');
