const {chromium}=require('playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');res.end(fs.readFileSync(path.resolve(__dirname,'../index.html')));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`http://127.0.0.1:${server.address().port}`);await page.locator('[data-page=past]').click();
 assert.ok(await page.locator('#past-file').isVisible());assert.ok(await page.locator('#past-pdf').isVisible());
 const sourceLinks=await page.locator('#past-downloads a').evaluateAll(links=>links.map(a=>a.href));assert.deepEqual(sourceLinks,['https://www.royalblue-education.com/school-exams','https://www.kusjh.kh.edu.tw/sidelist/67','https://educase.kh.edu.tw/navigate/a/#/s/E51D4D8E663D477288CA032C047DBC63AUY','https://www.hkhs.kh.edu.tw/ischool/publish_page/11/?cid=124']);
 const sourceData=await page.evaluate(()=>JSON.parse(document.querySelector('#public-exam-sources-data').textContent).sources);assert.equal(sourceData.length,50);assert.equal(sourceData.filter(x=>x.url.startsWith('https://www.royalblue-education.com/school-exams/')).length,39);assert.equal(sourceData.reduce((n,x)=>n+(x.downloads||[]).length,0),28);assert.ok(!sourceData.some(x=>/exambank/i.test(x.id+' '+x.url+' '+x.title)));
 await page.locator('#past-school').selectOption('鼓山高中');assert.equal(await page.locator('#public-source-list details summary').innerText(),'校方原站檔案（28）');assert.equal(await page.locator('#public-source-list details a').count(),28);
 await page.locator('#past-school').selectOption('高雄中學');assert.ok((await page.locator('#public-source-list').innerText()).includes('高雄中學｜114上高一第一次段考數學試題'));
 await page.locator('[data-page=exam]').click();await page.locator('#exam-source').selectOption('past');await page.locator('#exam-past-school').selectOption('高雄中學');assert.ok(await page.locator('#exam-external-papers').isVisible());assert.equal(await page.locator('#exam-external-papers article.question').count(),3);
 await page.locator('#exam-past-school').selectOption('鼓山高中');assert.equal(await page.locator('#exam-external-papers details summary').innerText(),'校方原站檔案（28）');assert.equal(await page.locator('#exam-external-papers details a').count(),28);await page.locator('[data-page=past]').click();

 await page.locator('#past-school').selectOption('鳳新高中');
 // Minimal valid PDF fixture for local reading; not a real school examination.
 const stream='BT /F1 14 Tf 40 100 Td (TEST ONLY PDF) Tj ET';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 200] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];
 let pdf='%PDF-1.4\n';const offsets=[0];objects.forEach((obj,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${obj}\nendobj\n`;});const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
 await page.waitForFunction(()=>pdfLibraryReady);await page.locator('#past-pdf').setInputFiles({name:'test-only.pdf',mimeType:'application/pdf',buffer:Buffer.from(pdf)});await page.waitForFunction(()=>document.querySelector('#pdf-status').textContent.includes('已載入'));assert.ok(await page.locator('#pdf-preview').isVisible());assert.match(await page.locator('#pdf-name').innerText(),/鳳新高中.*test-only.pdf/);const pdfUrl=await page.locator('#pdf-open').getAttribute('href');assert.ok(pdfUrl.startsWith('blob:'));assert.equal(await page.evaluate(async url=>(await (await fetch(url)).text()).slice(0,5),pdfUrl),'%PDF-');
 await page.locator('#past-pdf').setInputFiles({name:'invalid.pdf',mimeType:'application/pdf',buffer:Buffer.from('<script>alert(1)</script>')});await page.waitForFunction(()=>document.querySelector('#pdf-status').textContent.includes('不是有效的 PDF'));assert.equal(await page.locator('#pdf-open').getAttribute('href'),pdfUrl);
 await page.locator('#pdf-clear').click();assert.ok(await page.locator('#pdf-preview').isHidden());assert.equal(await page.locator('#pdf-object').getAttribute('data'),null);
 assert.equal(await page.evaluate(()=>storedPDFs.length),1);
 await page.locator('#past-pdf').setInputFiles([{name:'same.pdf',mimeType:'application/pdf',buffer:Buffer.from(pdf)},{name:'second.pdf',mimeType:'application/pdf',buffer:Buffer.from(pdf+'\n% second fixture\n')}]);await page.waitForFunction(()=>document.querySelector('#pdf-status').textContent.includes('略過重複 1 份'));assert.equal(await page.evaluate(()=>storedPDFs.length),2);
 await page.reload();await page.locator('[data-page=past]').click();await page.waitForFunction(()=>pdfLibraryReady);assert.equal(await page.evaluate(()=>storedPDFs.length),2);await page.locator('[data-pdf-read]').first().click();await page.waitForFunction(()=>!document.querySelector('#pdf-preview').hidden);assert.ok(await page.locator('#pdf-preview').isVisible());
 const storedId=await page.evaluate(()=>storedPDFs[0].id);await page.locator('#pdf-search').fill(await page.evaluate(()=>storedPDFs[0].name));await page.locator(`[data-pdf-school="${storedId}"]`).selectOption('高雄中學');await page.waitForFunction(()=>storedPDFs.some(p=>p.school==='高雄中學'));await page.locator('#pdf-school-filter').selectOption('高雄中學');assert.equal(await page.locator('[data-pdf-delete]').count(),1);
 page.once('dialog',d=>d.accept());await page.locator('[data-pdf-delete]').first().click();await page.waitForFunction(()=>storedPDFs.length===1);await page.locator('#pdf-school-filter').selectOption('all');

 assert.equal(await page.evaluate(()=>state.bank.filter(q=>q.kind==='past').length),0);assert.ok(await page.locator('#start-past').isDisabled());assert.ok(await page.locator('#past-empty').isVisible());
 // All fixtures are synthetic test data, never shipped as real past papers.
 const csv=await page.evaluate(()=>{const questions=[0,1,2].map((n)=>({...structuredClone(seed[n]),id:`TEST-PAST-${n}`,kind:'past',school:n===2?'高雄中學':'鳳新高中',year:n===1?'113':'114',semester:n===1?'下學期':'上學期',grade:n===1?'高二':'高一',exam:'第一次段考',source:'https://example.test/synthetic-test-only',question:'[TEST ONLY] '+seed[n].question}));return csvString(questions,true);});
 await page.locator('#past-file').setInputFiles({name:'test-past.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await page.waitForFunction(()=>document.querySelector('#past-status').textContent.includes('已合併'));
 assert.equal(await page.locator('#past-list .question').count(),2);assert.equal(await page.locator('#past-year option').count(),3);
 assert.equal(await page.locator('#past-list a').first().getAttribute('href'),'https://example.test/synthetic-test-only');
 await page.locator('#past-year').selectOption('114');assert.equal(await page.locator('#past-list .question').count(),1);
 await page.locator('#past-grade').selectOption('高二');assert.ok(await page.locator('#start-past').isDisabled());await page.locator('#past-grade').selectOption('高一');
 await page.locator('#past-number').fill('1');await page.locator('#start-past').click();const q=await page.evaluate(()=>activeExam.questions[0]);assert.equal(q.school,'鳳新高中');assert.equal(q.year,'114');assert.match(await page.locator('#exam-content .notice').innerText(),/歷屆/);
 const wrong=['A','B','C','D'].find(a=>a!==q.answer);await page.locator(`[name=answer-0][value=${wrong}]`).check();await page.locator('#answer-form button').click();assert.equal(await page.evaluate(()=>Object.values(state.mistakes)[0].question.school),'鳳新高中');
 await page.locator('#view-mistakes').click();await page.locator('#retry-mistakes').click();await page.locator(`[name=answer-0][value=${q.answer}]`).check();await page.locator('#answer-form button').click();assert.equal(await page.evaluate(()=>Object.keys(state.mistakes).length),0);
 // Daily selection distinguishes original and imported past papers.
 await page.locator('#exam-source').selectOption('past');assert.ok(await page.locator('#exam-school-field').isVisible());await page.locator('#exam-past-school').selectOption('高雄中學');assert.equal(await page.evaluate(()=>pool().length),1);
 await page.locator('#exam-source').selectOption('original');assert.ok(await page.locator('#exam-school-field').isHidden());assert.equal(await page.evaluate(()=>pool().length),30);
 // Reject missing provenance, unsafe source, ID collisions, without mutating bank.
 for(const type of ['missing','unsafe','collision']){
  const outcome=await page.evaluate(type=>{const before=JSON.stringify(state.bank),q={...structuredClone(seed[0]),id:'TEST-FAIL',kind:'past',school:'鳳新高中',year:'114',semester:'上學期',grade:'高一',exam:'第一次段考',source:'https://example.test/test'};if(type==='missing')q.source='';if(type==='unsafe')q.source='javascript:alert(1)';if(type==='collision')q.id=seed[0].id;let error;try{importPastCSV(csvString([q],true));}catch(e){error=e.message;}return {error,unchanged:before===JSON.stringify(state.bank)};},type);assert.ok(outcome.error,type);assert.ok(outcome.unchanged,type);
 }
 assert.equal(await page.evaluate(()=>parseCSV(csvString(state.bank)).filter(q=>q.kind==='past').length),3);
 await page.reload();assert.equal(await page.evaluate(()=>state.bank.filter(q=>q.kind==='past').length),3);
 await page.locator('[data-page=past]').click();await page.locator('#school-file').setInputFiles({name:'schools.csv',mimeType:'text/csv',buffer:Buffer.from('\uFEFF學校名稱,官網網址\r\n測試用学校,https://example.test/school\r\n')});await page.waitForFunction(()=>document.querySelector('#school-status').textContent.includes('已合併'));assert.ok(await page.evaluate(()=>state.schools.some(s=>s.name==='測試用学校')));
 await page.locator('#past-school').selectOption('高雄中學');await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/Users/prorock/.hermes/cache/scratch/fengxin-past-mobile.png',fullPage:false});
 assert.deepEqual(errors,[]);await browser.close();await new Promise(r=>server.close(r));console.log('PASS: past paper metadata, dependent filters, exam/retry, CSV round-trip, source validation, school directory, persistence, mobile layout.');
})().catch(e=>{console.error(e);process.exit(1);});
